### ISSUE TITLE
Wrong "Where" for online workshopts

### ISSUE THREAD

**Issue by isazi** [esciencecenter-digital-skills/next-workshop-template#100]
When the value `NA` is in `_data/data.csv` the field is not ignored for the "**Where**" field, therefore producing something like:

`Where: NA. Get directions with OpenStreetMap or Google Maps.`

**Comment by SarahAlidoost** [comment]
@isazi thanks. I checked the [data.csv](https://github.com/esciencecenter-digital-skills/2022-02-08-ds-gpu/blob/main/_data/data.csv) file of **2022-02-08-ds-gpu** and noticed that the field `address` is filled with `NA`.  I will tag @liekelotte to help with this issue.

@liekelotte, as Discussed with @mkuzak, the field `address` in data.csv file should be `the full street address of workshop, videoconferencing URL, or 'online'`, please see the information at the top of the template [index.md](https://raw.githubusercontent.com/esciencecenter-digital-skills/next-workshop-template/main/index.md). Can you please check if data.csv generator could be fixed? thanks.
