### ISSUE TITLE
the Carpentries CoC appears in gpu workshop page

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/next-workshop-template#101]
It looks like the logic for the navbar does not work properly. The Carpentries CoC should not be appearing in the navbar when it's ds workshop.

**Comment by SarahAlidoost** [comment]
@mkuzak thanks, a PR is made to fix the issue, see https://github.com/esciencecenter-digital-skills/next-workshop-template/pull/102, I added you as the reviewer.
