### ISSUE TITLE
Add heading for necessary software setup.

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/next-workshop-template#107]
Currently, when setup instructions are added automatically from the metadata repository they end up under `Install the videoconferencing client` and `Set up your workspace`. It should have its own `h3` level heading. Example for R Packages workshop ([https://esciencecenter-digital-skills.github.io/2022-03-22-ds-rpackaging/](https://esciencecenter-digital-skills.github.io/2022-03-22-ds-rpackaging/)) below.
```html
<h3 id="software-setup">Install R, RStudio and required packages</h3>
```
This can be generic and located in the workshop template or specific and located in the `setup.md` in the metadata repository.

**Comment by SarahAlidoost** [comment]
@mkuzak thanks for reporting the issue. I asked for your review on PR #108.
