### ISSUE TITLE
Consider removing schedule from collaborative document

### ISSUE THREAD

**Issue by PabRod** [esciencecenter-digital-skills/next-workshop-template#2]
## Problem

Appending the schedule to the collaborative document typically requires transforming it from `html` to `markdown`. Although it is not difficult, automating this is a non-trivial process that may be particularly unwelcoming to new lead instructors.

## Possible solutions

- The quick and easy one: just link to the `html` schedule.
- The also quick and less easy: link an online `html` to `markdown` converter website.

**Comment by SarahAlidoost** [comment]
this is fixed by `schedule.md` in the workshop metadata repo.
