### ISSUE TITLE
Create Code Refinery Workshop landing page with _meta data

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/next-workshop-template#73]
- [ ] 1. Workshop landing page based on Ecology Workshop Overview (datacarpentry.org) 
- [ ] 2. Most information is in `index.md` 
- [ ] 3. Use importer 
- [ ] 4. eScience Center branding 
- [ ] 5. Link the lesson we teach 
- [ ] 6 Add `_meta` and files in line with issue Add lesson information to support new workshop template at eScience Center · Issue #24 · carpentries-incubator/lesson-gpu-programming (github.com)

**Comment by JensWehner** [comment]
Sorry I have to do sth. here?

**Comment by mkuzak** [comment]
Hi @JensWehner, yes you were. If you still have time, it would be great if you created a landing page for our Code Refinery workshops. If you don't have time, let me know, we will need to find someone else to do it.

**Comment by JensWehner** [comment]
Would be nice if someone else can do that. Sorry, this went completely over my head. Apologies.

**Comment by mkuzak** [comment]
Ok, we'll find someone else ;)

**Comment by SarahAlidoost** [comment]
There is no `_meta` folder in the workshop template repo anymore.
