### ISSUE TITLE
Remove template warning

### ISSUE THREAD

**Issue by dafnevk** [esciencecenter-digital-skills/next-workshop-template#74]
The following message appears on the workshop page:

> This is the workshop template. Delete these lines and use it to customize your own website. If you are running a self-organized workshop or have not put in a workshop request yet, please also fill in this workshop request form to let us know about your workshop and our administrator may contact you if we need any extra information. If this is a pilot workshop for a new lesson, remember to uncomment the `pilot_lesson_site` field in `_config.yml`

This message should be deleted if the data for the workshop has been filled in.

**Comment by SarahAlidoost** [comment]
it is fixed in the current workshop template.
