### ISSUE TITLE
Write text for `_includes/ds/intro.md`

### ISSUE THREAD

**Issue by jhidding** [esciencecenter-digital-skills/next-workshop-template#84]
This should introduce the digital skills at NLeSC in general, the current text is adapted from the esciencecenter.nl website.

**Comment by SarahAlidoost** [comment]
@mkuzak please provide the text.

**Comment by mkuzak** [comment]
Digital Skills Workshops by the Netherlands eScience Center focus on the foundational digital skills needed to put reproducible research into practice. They cover the essentials of version control, online collaboration, reproducible code and good programming practices, and intermediate and advanced technologies or method-specific skills, such as GPU and Parallel Programming and Deep Learning.

**Comment by SarahAlidoost** [comment]
@mkuzak thanks for the text. I asked for your review on PR #109

**Comment by mkuzak** [comment]
While preparing the newsletter, we updated this text. It is now":

> The eScience Center offers a range of free workshops and training courses, open to all researchers affiliated with Dutch research organizations. We organize workshops covering digital skills needed to put reproducible research into practice. These include online collaboration, reproducible code and good programming practices. We also offer more advanced workshops such as GPU Programming, Parallel Programming and Deep Learning.

@SarahAlidoost  can you update this text?

**Comment by SarahAlidoost** [comment]
> While preparing the newsletter, we updated this text. It is now:
> 
> > The eScience Center offers a range of free workshops and training courses, open to all researchers affiliated with Dutch research organizations. We organize workshops covering digital skills needed to put reproducible research into practice. These include online collaboration, reproducible code and good programming practices. We also offer more advanced workshops such as GPU Programming, Parallel Programming and Deep Learning.
> 
> @SarahAlidoost can you update this text?

Sure, it is now updated, See #109
