### ISSUE TITLE
Transfer repositories.csv to _config.yaml

### ISSUE THREAD

**Issue by jhidding** [esciencecenter-digital-skills/next-workshop-template#86]

**Comment by SarahAlidoost** [comment]
related issue #89. If we move `_meta` dir from `lesson-template` to the `workshop-template` repo itself, we dont need `repositories.csv` info.

**Comment by SarahAlidoost** [comment]
This issue is addressed in PR https://github.com/esciencecenter-digital-skills/next-workshop-template/pull/95
