### ISSUE TITLE
Move _meta dir outside of lesson repository

### ISSUE THREAD

**Issue by SarahAlidoost** [esciencecenter-digital-skills/next-workshop-template#89]
The carpentries style lessons already have a setup.md file in their root directory.
Can we use that file instead of a new one in _meta/ dir to avoid redundancy?

**Comment by SarahAlidoost** [comment]
@mkuzak and I discussed the issue of `_meta` dir. We will move the `_meta` dir to the workshop-template. This makes it possible if someone wants to change the content of any files for a specific workshop. Then, the workshop repository will hold all the workshop-specific information.

**Comment by jhidding** [comment]
Please do not loose touch with the idea of consistency of information. For example, the setup instructions should be in the lesson repo: we need a single place for updating those.

**Comment by dsmits** [comment]
@jhidding there seem to be two types of setup instructions. The official one for the carpentries page and our specific setup instructions. Either we make sure that those two are merged into one or we keep the escience specific instructions in a separate repo and not in the official carpentries incubator repo.

Example:
- ["general" parallel python instructions](https://carpentries-incubator.github.io/lesson-parallel-python/setup.html)
- [parallel python setup instructions used in workshop announcement](https://github.com/carpentries-incubator/lesson-parallel-python/blob/gh-pages/_meta/setup.md)

**Comment by mkuzak** [comment]
@dsmits we discussed it with @jhidding  and @SarahAlidoost and we decided to keep Generic/Carpentries content in the lesson repository and Center's specific in https://github.com/esciencecenter-digital-skills/workshop-metadata

**Comment by SarahAlidoost** [comment]
> @dsmits we discussed it with @jhidding and @SarahAlidoost and we decided to keep Generic/Carpentries content in the lesson repository and Center's specific in https://github.com/esciencecenter-digital-skills/workshop-metadata

Related issue #91
