### ISSUE TITLE
Repositories.csv should refer to esciencecenter-digital-skills instead of escience-digital-skills

### ISSUE THREAD

**Issue by dsmits** [esciencecenter-digital-skills/next-workshop-template#90]
I see the index.md uses the `repositories.csv` file to get the right metadata.

However, the escience github organization should be `esciencecenter-digital-skills`, not `escience-digital-skills`.

For example, the first item is now:
```csv
curriculum,slug
ds-parallel,escience-digital-skills/lesson-parallel-python
```

While it should be
```
curriculum,slug
ds-parallel,esciencecenter-digital-skills/lesson-parallel-python
```

**Comment by SarahAlidoost** [comment]
Thanks @dsmits. This will be fixed by #89 .
